apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-worker
  template:
    metadata:
      labels:
        app: user-worker
    spec:
      containers:
      - name: user-worker
        image: docker.io/library/user-worker-service:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: "DOTNET_ENVIRONMENT"
          value: "Production"
        - name: "DOTNET_ConnectionStrings__DefaultConnection"
          value: "Server=mysql;User ID=root;Password=pass;Database=uqar"