apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-consumer-deployment
spec:
  selector:
    matchLabels:
      app: notification-consumer
  template:
    metadata:
      labels:
        app: notification-consumer
    spec:
      containers:
      - name: notification-consumer
        image: stephanebrillant/inf36307:tp3-notification-consumer